### ISSUE TITLE
DeprecationWarning: 'U' mode is deprecated

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/manuel#2]
Noticed this in passing:

```
/home/mg/src/zopefoundation/persistent/.tox/py37/lib/python3.7/site-packages/manuel/testing.py:182: DeprecationWarning: 'U' mode is deprecated
  with open(abs_path, 'U') as fp:
```

**Comment by jamadden** [comment]
The canonical repo for this is now https://github.com/benji-york/manuel where this issue was fixed in https://github.com/benji-york/manuel/pull/15 . It just needs a PyPI release. @benji-york or @jimfulton , could we get a PyPI release when convenient, please?

**Comment by icemac** [comment]
README.rst is fixed, I am archiving the repos now.
